./fastchess-ubuntu-22.04 \
  -engine cmd=./engines/artifact name=Artifact \
  -engine cmd=./engines/artifact-mateless name=ArtiMateless \
  -openings file=./engines/UHO_Lichess_4852_v1.epd format=epd order=random \
  -each tc=10+0.1 \
  -pgnout ./engines/out.pdn \
  -log file=./engines/log.txt engine=true \
  -rounds 20000 \
  -repeat \
  -concurrency 6 \
  -sprt elo0=0 elo1=10 alpha=0.05 beta=0.1